name: phonepay_demo
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/home1.jpg
    - assets/fastTag.jfif
    - assets/a23Rummy.jpg
    - assets/Fruit Fight.png
    - assets/indusApp.png
    - assets/ludo.png
    - assets/mpl.jpg
    - assets/phonepeGreen.png
    - assets/pincode.png
    - assets/rummyCircle.jfif
    - assets/sharedotmarket_logo.jfif
    - assets/tajRummy.png
    - assets/winzo.jfif
    - assets/zupee.png
    - assets/googlePlay.jfif